import { and, asc, desc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { items, reports, stocks } from "../../../db/schema";
import { isStaff, publicConfig } from "../_shared";

const SEED=[["Bécher 100 mL","Verrerie courante",2.4],["Bécher 250 mL","Verrerie courante",3.1],["Erlenmeyer 250 mL","Verrerie courante",4.2],["Éprouvette graduée 100 mL","Verrerie courante",8.9],["Fiole jaugée 100 mL — classe A","Verrerie jaugée",15.8],["Pipette jaugée 10 mL — classe A","Verrerie jaugée",7.6],["Pipette graduée 10 mL","Verrerie jaugée",4.9],["Burette 25 mL","Verrerie jaugée",22.5],["Ampoule à décanter 250 mL","Verrerie courante",28.4],["Ballon fond rond 250 mL","Verrerie courante",12.7],["Tube à essai","Verrerie courante",.85],["Entonnoir en verre 75 mm","Verrerie courante",5.3]] as const;
async function seed(){const db=await getDb(),config=await publicConfig();if((await db.select().from(items).limit(1)).length)return;const added=await db.insert(items).values(SEED.map(x=>({name:x[0],category:x[1],price:x[2]}))).returning();const today=new Date().toISOString().slice(0,10);await db.insert(stocks).values(config.labs.flatMap((lab,li)=>added.map((it,i)=>({lab,itemId:it.id,quantity:4+((i*7+li*3)%34),threshold:5+(i%4)*2,updated:today,lastOrderPrice:it.price}))))}
export async function GET(req:Request){await seed();const db=await getDb(),config=await publicConfig(),publicItems=await db.select().from(items).where(eq(items.active,true)).orderBy(asc(items.name)),allStock=await db.select().from(stocks),availability=allStock.filter(x=>x.enabled).map(x=>({lab:x.lab,itemId:x.itemId})),headers={"cache-control":"no-store, no-cache, must-revalidate"};if(!(await isStaff(req)))return Response.json({items:publicItems,availability,config},{status:401,headers});return Response.json({items:publicItems,reports:await db.select().from(reports).orderBy(desc(reports.date)),stock:allStock,availability,config},{headers})}
export async function POST(req:Request){if(!(await isStaff(req)))return Response.json({error:"Non autorisé"},{status:401});const b=await req.json() as any,db=await getDb(),today=new Date().toISOString().slice(0,10);
if(b.action==="addItem"){const name=String(b.item?.name||"").trim().slice(0,100),category=String(b.item?.category||"Autre").slice(0,50),price=Number(b.item?.price);if(!name||!Number.isFinite(price)||price<0)return Response.json({error:"Matériel invalide"},{status:400});const [item]=await db.insert(items).values({name,category,price}).returning();return Response.json({ok:true,item})}
if(b.action==="deleteItem"){await db.update(items).set({active:false}).where(eq(items.id,Number(b.id)));return Response.json({ok:true})}
if(b.action==="saveStock"){const x=b.stock,itemId=Number(x.itemId),lab=String(x.lab),[existing]=await db.select().from(stocks).where(and(eq(stocks.lab,lab),eq(stocks.itemId,itemId))).limit(1),values={quantity:Number(x.quantity),enabled:true,threshold:Number(x.threshold),updated:String(x.updated||today),lastOrder:String(x.lastOrder||""),lastOrderQty:Number(x.lastOrderQty)||0,lastOrderPrice:Number(x.lastOrderPrice)||0};if(existing)await db.update(stocks).set(values).where(eq(stocks.id,existing.id));else await db.insert(stocks).values({lab,itemId,...values});await db.update(items).set({price:values.lastOrderPrice}).where(eq(items.id,itemId));return Response.json({ok:true})}
if(b.action==="addLabItem"){const lab=String(b.lab),itemId=Number(b.itemId);if(!(await publicConfig()).labs.includes(lab))return Response.json({error:"Laboratoire inconnu"},{status:400});const [it]=await db.select().from(items).where(eq(items.id,itemId)).limit(1);if(!it)return Response.json({error:"Matériel inconnu"},{status:404});const [existing]=await db.select().from(stocks).where(and(eq(stocks.lab,lab),eq(stocks.itemId,itemId))).limit(1);if(existing)await db.update(stocks).set({enabled:true,updated:today}).where(eq(stocks.id,existing.id));else await db.insert(stocks).values({lab,itemId,quantity:0,enabled:true,threshold:5,updated:today,lastOrderPrice:it.price});return Response.json({ok:true})}
if(b.action==="removeLabItem"){const lab=String(b.lab),itemId=Number(b.itemId);await db.update(stocks).set({enabled:false,updated:today}).where(and(eq(stocks.lab,lab),eq(stocks.itemId,itemId)));return Response.json({ok:true})}
if(b.action==="deleteReport"){const [r]=await db.select().from(reports).where(eq(reports.id,Number(b.id))).limit(1);if(!r)return Response.json({error:"Déclaration introuvable"},{status:404});const [s]=await db.select().from(stocks).where(and(eq(stocks.lab,r.lab),eq(stocks.itemId,r.itemId))).limit(1);await db.batch([db.delete(reports).where(eq(reports.id,r.id)),s?db.update(stocks).set({quantity:s.quantity+r.quantity,updated:today}).where(eq(stocks.id,s.id)):db.insert(stocks).values({lab:r.lab,itemId:r.itemId,quantity:r.quantity,threshold:5,updated:today,lastOrderPrice:r.unitPrice})]);return Response.json({ok:true})}
if(b.action==="updateReport"){const x=b.report,id=Number(x?.id),[old]=await db.select().from(reports).where(eq(reports.id,id)).limit(1),[it]=await db.select().from(items).where(eq(items.id,Number(x?.itemId))).limit(1);if(!old||!it)return Response.json({error:"Déclaration ou matériel introuvable"},{status:404});const qty=Math.max(1,Number(x.quantity)||1),lab=String(x.lab),[oldS]=await db.select().from(stocks).where(and(eq(stocks.lab,old.lab),eq(stocks.itemId,old.itemId))).limit(1),[newS]=await db.select().from(stocks).where(and(eq(stocks.lab,lab),eq(stocks.itemId,it.id))).limit(1);const ops:any[]=[db.update(reports).set({date:String(x.date),classroom:String(x.classroom),lab,station:String(x.station).slice(0,12),itemId:it.id,itemName:it.name,unitPrice:it.price,quantity:qty}).where(eq(reports.id,id))];ops.push(oldS?db.update(stocks).set({quantity:oldS.quantity+old.quantity,updated:today}).where(eq(stocks.id,oldS.id)):db.insert(stocks).values({lab:old.lab,itemId:old.itemId,quantity:old.quantity,threshold:5,updated:today,lastOrderPrice:old.unitPrice}));const correctedBase=newS?.id===oldS?.id?(newS?.quantity||0)+old.quantity:(newS?.quantity||0);ops.push(newS?db.update(stocks).set({quantity:correctedBase-qty,updated:today}).where(eq(stocks.id,newS.id)):db.insert(stocks).values({lab,itemId:it.id,quantity:-qty,threshold:5,updated:today,lastOrderPrice:it.price}));await db.batch(ops as any);return Response.json({ok:true})}
return Response.json({error:"Action inconnue"},{status:400})}
